apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-service
  template:
    metadata:
      labels:
        app: url-service
    spec:
      containers:
      - name: url-service
        image: miniurl/url-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: global-config
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-url:3306/url_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: url-service
spec:
  selector:
    app: url-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
